"""PBF4 — peace-quant's PBF-MX, derived dynamically from the PBF8 spine.

The 4-bit LUT is generated by sampling 8 magnitudes from the standard PBF8
spine (``_pbf8``) at every-other level — same construction as peace-quant's
[mx_pbf_lut](crates/pbf8/src/mx4.rs#L25). Step ratio between levels is
``exp(2·LEVEL_LOG_STEP) = 2^(3/8) ≈ 1.297`` (~30%/level). Magnitudes are
normalised so the top entry is exactly 1.0, then mirrored into NF4-style
asymmetric layout (7 neg + 0 + 8 pos = 16 unique values).

Same LUT for every tensor — no per-tensor calibration. The LUT lives in
``QuantState.code`` so CUDA's LUT-generic ``kgemm_4bit_inference_naive`` kernel
runs unchanged.
"""

from typing import Optional

import torch

from . import _pbf8

# 4-bit NF4-layout: 7 neg + 0 + 8 pos = 16 unique LUT entries.
NUM_LUT_MAGS: int = 8

# Sample 8 magnitudes from the PBF8 spine at every-other level (stride 2),
# starting at level 2 so the highest entry comes from PBF8 mag-index 16
# (= ``RING_POW[1]``). The first sampled magnitude is at level 2 (≈ 1.297
# in raw PBF8 space); after normalising the top to 1.0 we get peace-quant's
# pbf_mx_lut shape: ``[0.162, 0.21, 0.273, 0.354, 0.458, 0.594, 0.771, 1.0]``.
_PBF4_PBF8_START_LEVEL: int = 2


def _build_pbf_mx_lut() -> torch.Tensor:
    """Generate the PBF4 LUT by sub-sampling the PBF8 spine."""
    raw_mags = _pbf8.sample_every_other_level(NUM_LUT_MAGS, start_level=_PBF4_PBF8_START_LEVEL)
    top = raw_mags[-1]
    mags = [m / top for m in raw_mags]
    values = [-m for m in reversed(mags[1:])] + [0.0] + mags
    return torch.tensor(values, dtype=torch.float32)


# PBF4 LUT — derived from PBF8 at module load. Same LUT for every tensor.
PBF_MX_LUT: torch.Tensor = _build_pbf_mx_lut()


# ---------------------------------------------------------------------------
# Block normalisation (per-block absmax → [-1, 1]).
# ---------------------------------------------------------------------------


def _block_normalise(A: torch.Tensor, blocksize: int) -> tuple[torch.Tensor, torch.Tensor, int]:
    n = A.numel()
    full_blocks = n // blocksize
    rem = n % blocksize
    blocks = full_blocks + (1 if rem else 0)
    A_flat = A.reshape(n).float()
    absmax = torch.zeros((blocks,), device=A.device, dtype=torch.float32)

    parts = []
    if full_blocks:
        full = A_flat[: full_blocks * blocksize].reshape(full_blocks, blocksize)
        absmax[:full_blocks] = full.abs().max(dim=-1).values
        denom = absmax[:full_blocks].clamp(min=1e-30).view(-1, 1)
        parts.append((full / denom).clamp(-1, 1).reshape(-1))
    if rem:
        rem_part = A_flat[-rem:]
        absmax[-1] = rem_part.abs().max()
        denom = absmax[-1].clamp(min=1e-30)
        parts.append((rem_part / denom).clamp(-1, 1))
    scaled = torch.cat(parts, dim=0) if parts else A_flat
    return scaled, absmax, full_blocks


# ---------------------------------------------------------------------------
# Quantize / dequantize using the fixed PBF-MX LUT.
# ---------------------------------------------------------------------------


def quantize_pbf4_blockwise(
    A: torch.Tensor,
    blocksize: int,
    quant_storage: torch.dtype,
    lut: Optional[torch.Tensor] = None,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Quantize ``A`` to PBF4. Returns ``(packed_codes, absmax, lut)``.

    LUT defaults to ``PBF_MX_LUT`` (top = 1.0), so the bnb kernel formula
    ``quant_map[byte] * absmax`` reproduces block-max directly.
    """
    if lut is None:
        lut = PBF_MX_LUT
    lut = lut.to(A.device)

    scaled, absmax, _ = _block_normalise(A, blocksize)
    diff = (scaled.unsqueeze(-1) - lut.to(scaled.dtype)).abs()
    codes = diff.argmin(dim=-1).to(torch.int64)

    if codes.numel() % 2 != 0:
        codes = torch.cat([codes, codes.new_zeros(1)])
    packed = ((codes[::2] << 4) | codes[1::2]).to(torch.uint8).unsqueeze(1)

    if quant_storage != torch.uint8:
        packed = packed.squeeze().view(quant_storage).unsqueeze(1)
    return packed, absmax, lut


def dequantize_pbf4_blockwise(
    A: torch.Tensor,
    absmax: torch.Tensor,
    lut: torch.Tensor,
    blocksize: int,
    shape,
    dtype: torch.dtype,
) -> torch.Tensor:
    """Inverse of ``quantize_pbf4_blockwise``: ``lut[byte] * absmax``."""
    if A.dtype != torch.uint8:
        A = A.view(torch.uint8)
    A = A.reshape(-1)

    out_codes = torch.empty(A.numel() * 2, dtype=torch.int64, device=A.device)
    out_codes[::2] = (A >> 4).long()
    out_codes[1::2] = (A & 0xF).long()

    n = 1
    for s in shape:
        n *= s
    out_codes = out_codes[:n]

    lut_dt = lut.to(dtype).to(A.device)
    decoded = lut_dt[out_codes]

    blocks = (n + blocksize - 1) // blocksize
    rem = n % blocksize
    has_rem = rem > 0
    out = torch.empty((n,), dtype=dtype, device=A.device)
    if has_rem:
        full_n = (blocks - 1) * blocksize
        if full_n:
            out[:full_n] = (decoded[:full_n].view(-1, blocksize) * absmax[: blocks - 1].to(dtype).view(-1, 1)).reshape(
                -1
            )
        out[full_n:] = decoded[full_n:] * absmax[-1].to(dtype)
    else:
        out = (decoded.view(blocks, blocksize) * absmax.to(dtype).view(-1, 1)).reshape(-1)

    return out.reshape(shape)
