name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: bitsandbytes
      repo_owner: bitsandbytes-foundation
      # avoid /src suffix leading to wrong links, like bitsandbytes/blob/main/src/bitsandbytes/nn/
      version_tag_suffix: ''  # defaults to '/src'
      custom_container: huggingface/transformers-doc-builder
    secrets:
      hf_token: ${{ secrets.HUGGINGFACE_PUSH }}
